server:
  port: 80


# 开启服务降级feign.circuitbreaker
feign:
  circuitbreaker:
    enabled: true



# Eureka配置
eureka:
  client:
    register-with-eureka: false   # 不向Eureka注册自己（因为不是提供者）
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/
