server:
  port: 7003

# Eureka配置
eureka:
  instance:
    hostname: eureka7003  # Eureka服务端的实例名称
  client:
    register-with-eureka: false   # 表示是否向Eureka注册中心注册自己
    fetch-registry: false   # fetch-registry为false时，则表示自己为注册中心
    service-url:  # 监控页面（与Eureka交互的路径）
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/  # 别人访问Eureka服务的路径