# 配置端口号
server:
  port: 8003

# mybatis配置
mybatis:
  # 配置实体类的别名
  type-aliases-package: com.guighost.springcloud.entity
  # 配置mapper文件路径
  mapper-locations: classpath:mybatis/mapper/*.xml
  # 配置mybatis的核心xml文件的路径（该核心配置文件可以省略，因为在application.yaml中都可以配置）
  config-location: classpath:mybatis/mybatis-config.xml

# spring的配置
spring:
  # 服务提供者的名字
  application:
    name: springcloud-provider-dept # 三个服务名称一致是前提
  # 配置数据库连接和数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud-db03?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: ghost


# Eureka配置：服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/
  # 修改eureka上的默认描述信息
  instance:
    instance-id: springcloud-provider-dept8003


# 配置监控服务的信息
info:
  app.name: GhostSpringcloud
  app.date: ${java.version.date}
  message: "已经完善的监控信息"

